# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# -- Improved X11 forwarding through GNU Screen (or tmux).
# If not in screen or tmux, update the DISPLAY cache.
# If we are, update the value of DISPLAY to be that in the cache.
# enable bash completion in interactive shells
# Tie into the DEBUG event to get a zsh-like preexec hook
# A more complete version at: http://glyf.livejournal.com/63106.html
preexec() { :; }    # Default empty function
postexec() { :; }   # Default empty function
preexec_invoke_exec () {
  [ -n "$COMP_LINE" ] && return  # Completing, do nothing
  preexec "$(history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g")";
}
trap 'preexec_invoke_exec' DEBUG
PROMPT_COMMAND='postexec'

preexec() {
  update-env-forwarding;
}

#magic for x11 forward in screen
function update-env-forwarding
{
    SCREEN_DISPLAY=~/.screen/.display
    SCREEN_SSH_AUTH_SOCK=~/.screen/.ssh_auth_sock
    if [ ! -d "~/.screen" ]; then
      mkdir -p ~/.screen
    fi
    if [ -z "$STY" -a -z "$TMUX" ]; then
		if [ ! -z ${DISPLAY+x} ]; then
	        echo $DISPLAY > $SCREEN_DISPLAY
		fi
    else
		if [ -f "$SCREEN_DISPLAY" ]; then
   	     	export DISPLAY=`cat $SCREEN_DISPLAY`
		fi
    fi
}

#Setting up editors
export VISUAL=/usr/bin/vim
export EDITOR=/usr/bin/vim

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

#Load custom PS1, this should look at using magicline
if [ -f ~/.config/liquidprompt/liquidprompt/liquidprompt ]; then
	source ~/.config/liquidprompt/liquidprompt/liquidprompt
else
	PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '
	source $HOME/.config/bash/git-prompt.sh
fi


#Source bash completion engine
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

shopt -s histverify


# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    [ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
    [ -e "$DIR_COLORS" ] || DIR_COLORS=""
    eval "`dircolors -b $DIR_COLORS`"
    alias ls='ls --color=auto'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
fi



# Put your fun stuff here.

#alias tmux-next to tmux if present
which tmux-next 2>/dev/null >/dev/null && alias tmux='tmux-next -2' || alias tmux="tmux -2"

#update the repo before doing anything else
pushd ~/.config > /dev/null

if ! git diff-files --quiet --ignore-submodules
    then
        echo >&2 "You have unstaged changes in ~/.config"
        err=1
    fi

if ! git diff-index --cached --quiet --ignore-submodules HEAD --
    then
        if [ $err = 0 ]
        then
            echo >&2 "Your have uncommitted changes in ~/.config"
        else
            echo >&2 "Additionally, your index contains uncommitted changes"
        fi
        err=1
    fi


ping -q -w1 -c1 google.com &>/dev/null && git pull || echo >&2 "No network, couldn't update .config"

popd > /dev/null

#Load all commands in bash-rc.d
for f in ~/.config/bash/bash-rc.d/*; do source $f; done

alias apt='sudo apt'
alias apt-get='sudo apt-get'
alias systemctl='sudo systemctl'
